# Generated by Django 3.1.5 on 2021-01-29 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('short_description', models.TextField()),
                ('long_description', models.TextField(blank=True)),
                ('slug', models.SlugField(max_length=40)),
                ('category', models.CharField(choices=[('Programming', 'Programming'), ('Photography', 'Photography'), ('Data', 'Data'), ('Misc', 'Misc')], max_length=15)),
                ('file_upload', models.FileField(blank=True, upload_to='')),
                ('photo_upload', models.ImageField(blank=True, upload_to='')),
            ],
        ),
    ]
