# Generated by Django 3.1.5 on 2021-01-29 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='file_upload',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='photo_upload',
            new_name='photo',
        ),
    ]
