# Generated by Django 3.1.5 on 2021-02-03 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_postcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postimage',
            name='post',
        ),
        migrations.DeleteModel(
            name='PostCode',
        ),
        migrations.DeleteModel(
            name='PostImage',
        ),
    ]
